#!/bin/bash
ETC=ETC_PLACEHOLDER
BIN=BIN_PLACEHOLDER
SBIN=SBIN_PLACEHOLDER

export PATH=$PATH:$BIN
if [ $UID -eq 0 ]; then
	export PATH=$PATH:$SBIN
fi

. $ETC/bash_completion
. $ETC/userrc

alias mkdir='mkdir -p'

# careful
alias cp='cp -i'
alias rm='rm -i'
alias mv='mv -i'

alias ll='ls -l'
alias la='ls -a'

ulimit -c unlimited

GLOBIGNORE=*..:*.

. $ETC/colorsrc
if [ $UID -ne 0 ]; then
	PROMPT_COLOR=__GREEN
else
	PROMPT_COLOR=__YELLOW
fi
PS1=`printf "\[${!PROMPT_COLOR}\]%s\[${__NORMAL}\]" "$PS1"`


export PAGER=less

export HISTTIMEFORMAT='%F %T '
export HISTSIZE=20000
export HISTFILESIZE=5000

test -t 0 && stty -ctlecho

true # so that sourcing the file wont return error

