#!/bin/bash

[[ $- == *i* ]] || return

ETC="CONFIG_ETC"
BIN="CONFIG_BIN"
SBIN="CONFIG_SBIN"

export PATH="${BIN}:${PATH}"
if [ $UID -eq 0 ]; then
	export PATH="${SBIN}:${PATH}"
fi

if [ "CONFIG_OS" = 'mac' ]; then
	PATH="/opt/homebrew/opt/binutils/bin:${PATH}"
	PATH="/opt/homebrew/opt/lsof/bin:${PATH}"
	PATH="/opt/homebrew/opt/bzip2/bin:${PATH}"
	PATH="/opt/homebrew/opt/curl/bin:${PATH}"
	PATH="/opt/homebrew/opt/bc/bin:${PATH}"
	PATH="/opt/homebrew/opt/make/libexec/gnubin:${PATH}"
	PATH="/opt/homebrew/opt/gawk/libexec/gnubin:${PATH}"
	PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:${PATH}"
	PATH="/opt/homebrew/opt/findutils/libexec/gnubin:${PATH}"
	PATH="/opt/homebrew/opt/grep/libexec/gnubin:${PATH}"
	PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:${PATH}"

	if [ -z "${LESSOPEN}" ]; then
		export LESSOPEN="|/opt/homebrew/bin/lesspipe.sh %s"
	fi
fi

source $ETC/bash_completion
shopt -s no_empty_cmd_completion
shopt -s hostcomplete

source $ETC/colorsrc

__PROMPT_COLOR_SET="\[$(__color_seq CONFIG_PROMPT_COLOR)\]"
__PROMPT_COLOR_RESET="\[$(__color_seq normal)\]"
PS1="${__PROMPT_COLOR_SET}\u@\h:\w\\\$${__PROMPT_COLOR_RESET} "

source $ETC/bashrc.user

alias mkdir='mkdir -p'

# careful
alias cp="cp -i $__COREUTILS_FLAGS"
alias rm="rm -i $__COREUTILS_FLAGS --one-file-system --preserve-root"
alias mv="mv -i $__COREUTILS_FLAGS"
alias ln="ln -i $__COREUTILS_FLAGS"

supported ls --group-directories-first && __LS_FLAGS+=" --group-directories-first"
alias ls="ls $__LS_FLAGS"
alias ll="ls -l $__LS_FLAGS"
alias la="ls -A $__LS_FLAGS"

cmd_exists vim && alias vi='vim' && alias view='vim -R'

ulimit -c unlimited

export PAGER=less

shopt -s cmdhist
export HISTTIMEFORMAT='%F %T '
export HISTCONTROL=ignorespace:ignoredups
export HISTSIZE=20000
export HISTFILESIZE=5000
export HISTIGNORE="exit:logout:reboot:shutdown:poweroff:return:clear:history:bg:fg:jobs:pwd:ls:ll:la:cd:ps"

export TIMEFORMAT=$'---\nreal\t%3lR\nuser\t%3lU\nsys\t%3lS\ncpu\t%P%%'

stty -ixon # disable ^S/^Q
test -t 0 && stty -ctlecho

unset ETC BIN SBIN USER_PROMPT_COLOR ROOT_PROMPT_COLOR
true # so that sourcing the file won't return error
