#!/bin/sh

export __NORMAL='\E[0m'
export __GRAY='\E[90m'
export __RED='\E[91m'
export __GREEN='\E[92m'
export __YELLOW='\E[93m'
export __BLUE='\E[94m'
export __MAGENTA='\E[95m'
export __CYAN='\E[96m'
export __WHITE='\E[97m'

for __TMP_COLOR in __NORMAL __GRAY __RED __GREEN __YELLOW __BLUE __MAGENTA __CYAN __WHITE; do
	__TMP_COLOR_NAME=${__TMP_COLOR:1}
	eval "$__TMP_COLOR_NAME=\"${!__TMP_COLOR/\\E/}\""
done
unset __TMP_COLOR __TMP_COLOR_NAME
