#!/bin/sh

declare -A __COLOR
__COLOR[black]=0
__COLOR[red]=1
__COLOR[green]=2
__COLOR[yellow]=3
__COLOR[blue]=4
__COLOR[magenta]=5
__COLOR[cyan]=6
__COLOR[white]=7
__COLOR[normal]=${__COLOR[white]}

__verify_color()
{
	if [ -z "${__COLOR[$1]}" ]; then
		echo "bad color $1" >&2
	fi
}

case $TERM in
	xterm*|rxvt*)
			color_seq()
			{
				__verify_color $1 || return 1
				echo -en "\033[9${__COLOR[$1]}m"
			}
		;;
	linux|*)
			color_seq()
			{
				__verify_color $1 || return 1
				tput setaf ${__COLOR[$1]}
			}
		;;
esac

for C in ${!__COLOR[@]}; do
	__TMP_COLOR_NAME=${C^^[a-z]}
	eval "__${__TMP_COLOR_NAME}=\"\$(color_seq $C)\""
	eval "_${__TMP_COLOR_NAME}=\"\${__${__TMP_COLOR_NAME}:1}\""
done

unset __TMP_COLOR_NAME
