#!/bin/bash

alias ls='ls -Fh'
alias size='du -hs'
alias lsd='ls -d'
alias lld='ll -d'
alias lla='ll -a'
alias tree='tree -CshF --dirsfirst'

# processes
alias psx='ps -ef | less'
cmd_exists htop && alias top='htop'

WORKSPACE=$HOME/tonian
REPOSITORY_ROOT=$WORKSPACE/dev
PROJECT_SUBDIR=subdir
PROJECT_ROOT=$REPOSITORY_ROOT/$PROJECT_SUBDIR
export WORKSPACE REPOSITORY_ROOT PROJECT_ROOT

mount_idank()
{
	:
}

__get_working_copy()
{
	if [ $# -eq 0 ]; then
		echo "$REPOSITORY_ROOT"
		return
	elif [ $# -eq 1 ] && [ -d "$REPOSITORY_ROOT/$1" ]; then
		echo "$REPOSITORY_ROOT/$1/$PROJECT_SUBDIR"
		return
	fi
	set `echo "$@" | sed 's/[1-9][1-9]*/ & /g'`
	LIST=`\ls -ut $REPOSITORY_ROOT`
	for ITEM in $@; do
		LIST=`echo "$LIST" | tr ' ' '\n' | grep -i $ITEM`
	done
	printf "$REPOSITORY_ROOT/%s/$PROJECT_SUBDIR\n" "`echo  "$LIST" | tr ' ' '\n' | sed 1q`"
}

__jump_working_copy()
{
	cd `__get_working_copy $@`
}

# 'j' jumps around the user's working directoy using short mnemonics
alias j="mount_idank && __jump_working_copy"

PS1='\D{%y-%m-%d %T} \u@\h:\w\$ '

# more informative trace when debugging bash scripts
export PS4='+ $$:${BASH_SOURCE}:${BASH_LINENO[1]}:${FUNCNAME}: '

# don't check mail
unset MAIL MAILCHECK MAILPATH
