set runtimepath^=LIB_PLACEHOLDER/vim

" general
" =======

set nocompatible        " Disable vi compatibility.
set nobackup            " Do not keep a backup file.
set iskeyword=@,48-57,_
set noerrorbells        " No beeps.
set magic               " Use 'magic' patterns (extended regular expressions).
set hidden		" allow movement to another buffer without saving the current one
set tags+=./tags;	" tell vim to find ctags even if in a subdirectory.
let mapleader = ","

" view
" ====

set showcmd             " Show (partial) command in status line.
set cmdheight=2		" height of the command line
set number		" show line numbers
set showmode            " Show current mode.
set modeline            " Enable modeline. BE CAREFUL WITH THAT!!!
set background=dark	" bright terminal colors
set wildmenu		" display file list when browsing files to open
set wildmode=list:longest " bash-like file completion
set laststatus=2	" When to show a statusline.

set splitright
set splitbelow
noremap <silent> - <C-w>-
noremap <silent> = <C-w>+

" status line, left side
set statusline=
set statusline+=%*%-3.3n%0*                    " buffer number
set statusline+=%f                             " file name
set statusline+=\ [%{strlen(&ft)?&ft:'none'}   " filetype
set statusline+=%R%M]                          " flags
" status line, right side
set statusline+=%=                             " right align
set statusline+=%*0x%-8B                       " current char
set statusline+=%-16.(%l/%L(%p%%),\ %c%V%)     " location of cursor in file - line#/total(percentage), column

" buffer view
" ===========

set tabstop=8		" tab width
set linebreak		" wrap on words, not characters
set showmatch           " Show matching brackets.
set matchpairs+=<:>	" '<' and '>' are considered matching brackets
set listchars=tab:>-,trail:$,extends:> " how to display whitespace when asked
set whichwrap=b,s,<,>,[,] " keys which can move the cursor to another line
set diffopt+=context:20	" 20 context lines in diff

if has("syntax")
	syntax on
endif

autocmd BufNewFile,BufRead gitconfig setfiletype gitconfig
autocmd BufNewFile,BufRead xdefaults,xdefaults.* setfiletype xdefaults
autocmd FileType log setlocal autoread nomodifiable readonly

" syntax highlight shell scripts as per POSIX, not the original Bourne shell which very few use
let g:is_posix = 1

" search & highlight
" ==================

set ignorecase          " Case insensitive matching.
set smartcase		" If search contains capitals, search exact case.
set incsearch           " Incremental search.
set hlsearch            " Highlight search matches.

highlight Normal guifg=White guibg=Black

" Disable highlighting
noremap <silent> ; :nohlsearch<CR>

set spelllang=en_us
set nospell
noremap <silent> <F6> :set spell!<CR>
map! <F6> <Esc><F6>

" formatting
" ==========

set autoindent		" indent a new line like the previous line
set smartindent		" rudimentary c-like indent
set shiftwidth=8	" indentation width
set textwidth=0         " Don't wrap words by default.

filetype plugin indent on

autocmd FileType make setlocal noexpandtab "'tab' means 'tab' in makefiles

" editing
" =======

set history=100         " Number of lines of command line history.
set undolevels=200      " Number of undo levels.
set gdefault            " Use 'g' flag by default with :s/foo/bar/.
set backspace=indent,eol,start " Allow backspacing over everything in insert mode.
set complete=k,.,w,b	" autocomplete from these places

autocmd! BufWritePost {,.}vimrc source ~/.vimrc " reload vimrc files if edited

inoremap <silent> <C-o> <C-x><C-o>

" hebrew support
noremap <silent> <F7> :set rightleft!<CR>:set hkmap!<CR>
map! <F7> <Esc><F7>

" interaction with other terminals
noremap <silent> <F8> :set paste!<CR>:set number!<CR>
map! <F8> <Esc><F8>

" these turned out to be annoying
" imap ( ()<left>
" imap [ []<left>
" imap < <><left>

" plugins
" =======

" --- cscope ---
" not strictly a plugin, but an external feature to be configured

if has("cscope")
	set cscopetag	" treat scsope tags like ctags
	set csto=0	" boolean: should ctags be queried before cscope?
	set cst		" consult cscope before ctags for :tag jump
	set nocsverb	" non verbose mode (when adding a database)

	if exists($CSCOPE_DB) " add database pointed to by environment
		cs add $CSCOPE_DB
	else " add any database in current directory
		let s:cscope_file=findfile("cscope.out", ".;")
		let s:cscope_pre=matchstr(s:cscope_file, ".*/")
		if !empty(s:cscope_file) && filereadable(s:cscope_file)
			exec "cs add" s:cscope_file s:cscope_pre
		endif
	endif

	" CScope related mappings.
	" Original CScope commands (as issued via ':cs find <querytype>'):
	"	0 or s: Find this C symbol
	"	1 or g: Find this definition
	"	2 or d: Find functions called by this function
	"	3 or c: Find functions calling this function
	"	4 or t: Find this text string
	"	6 or e: Find this egrep pattern
	"	7 or f: Find this file
	"	8 or i: Find files #including this file

	" map \cX to :cs find X
	nmap <Leader>cs :cs find s <C-R>=expand("<cword>")<CR><CR>
	nmap <Leader>c0 :cs find s <C-R>=expand("<cword>")<CR><CR>
	nmap <Leader>cg :cs find g <C-R>=expand("<cword>")<CR><CR>
	nmap <Leader>c1 :cs find g <C-R>=expand("<cword>")<CR><CR>
	nmap <Leader>cd :cs find d <C-R>=expand("<cword>")<CR><CR>
	nmap <Leader>c2 :cs find d <C-R>=expand("<cword>")<CR><CR>
	nmap <Leader>cc :cs find c <C-R>=expand("<cword>")<CR><CR>
	nmap <Leader>c3 :cs find c <C-R>=expand("<cword>")<CR><CR>
	nmap <Leader>ct :cs find t <C-R>=expand("<cword>")<CR><CR>
	nmap <Leader>c4 :cs find t <C-R>=expand("<cword>")<CR><CR>
	nmap <Leader>ce :cs find e <C-R>=expand("<cword>")<CR><CR>
	nmap <Leader>c6 :cs find e <C-R>=expand("<cword>")<CR><CR>
	nmap <Leader>cf :cs find f <C-R>=expand("<cfile>")<CR><CR>
	nmap <Leader>c7 :cs find f <C-R>=expand("<cfile>")<CR><CR>
	nmap <Leader>ci :cs find i ^<C-R>=expand("<cfile>")<CR>$<CR>
	nmap <Leader>c8 :cs find i ^<C-R>=expand("<cfile>")<CR>$<CR>
endif

" --- TabBar ---

" For TabBar plugin: set up tab bar depending on screen width:
if &columns <= 115 "screen NOT wide enough for vertical tabbar:
	" make tab bar multiline (use as many lines as necessary) and make sure
	" no tab is 'cut' to next line:
	let g:Tb_TabWrap = 1
	let g:Tb_MaxSize = 0
	let g:Tb_SplitBelow = 0
else " screen wide-enough for vertical tabbar:
	" open tab bar side-by-side with main window, on the right:
	let g:Tb_VSplit = 1
	let g:Tb_MinSize = 25
	let g:Tb_MaxSize = 25
	let g:Tb_SplitBelow = 1
endif

" For TabBar plugin: prevent from opening when in diff mode.
if &diff
	let g:V_DirDiffRunning = 1
endif

" For TabBar plugin: allow single-click tab switching
let g:Tb_UseSingleClick = 1

" cycles tabs
nmap <Tab> :Tbbn<CR>
nmap <S-Tab> :Tbbp<CR>


" --- FSwitch ---

let g:fsnonewfiles = 1
noremap <C-h> :FSHere<CR>

" --- Man ---

runtime ftplugin/man.vim
nnoremap K :Man <cword><CR>

" Correct typos
" =============
" this gets its own section because its large and stupid.

iab beacuse	because
iab becuase	because
iab acn		can
iab cna		can
iab centre	center
iab chnage	change
iab chnages	changes
iab chnaged	changed
iab chnagelog	changelog
iab Chnage	Change
iab Chnages	Changes
iab ChnageLog	ChangeLog
iab debain	debian
iab Debain	Debian
iab defualt	default
iab Defualt	Default
iab differnt	different
iab diffrent	different
iab emial	email
iab Emial	Email
iab figth	fight
iab figther	fighter
iab fro		for
iab fucntion	function
iab ahve	have
iab homepgae	homepage
iab logifle	logfile
iab lokk	look
iab lokking	looking
iab mial	mail
iab Mial	Mail
iab miantainer	maintainer
iab amke	make
iab mroe	more
iab nwe		new
iab recieve	receive
iab recieved	received
iab erturn	return
iab retrun	return
iab retunr	return
iab seperate	separate
iab shoudl	should
iab soem	some
iab taht	that
iab thta	that
iab teh		the
iab tehy	they
iab truely	truly
iab waht	what
iab wiht	with
iab whic	which
iab whihc	which
iab yuo		you
iab databse	database
iab versnio	version
iab obnsolete	obsolete
iab flase	false
iab recrusive	recursive
iab Recrusive	Recursive

" Days
iab monday	Monday
iab tuesday	Tuesday
iab wednesday	Wednesday
iab thursday	Thursday
iab friday	Friday
iab saturday	Saturday
iab sunday	Sunday

" Months
iab january	January
iab february	February
" iab march	March
iab april	April
" iab may	May
iab june	June
iab july	July
iab august	August
iab september	September
iab october	October
iab november	November
iab december	December
