#!/bin/sh
ETC_PLACEHOLDER=~/etc
BIN_PLACEHOLDER=~/bin
SBIN_PLACEHOLDER=~/sbin
USERNAME_PLACEHOLDER="${USER}"
HOSTNAME_PLACEHOLDER="${HOSTNAME}"
DNS_DOMAIN_PLACEHOLDER="`dnsdomainname`"
USER_FULL_NAME_PLACEHOLDER="`getent passwd "${USERNAME_PLACEHOLDER}" | cut -d: -f5 | cut -d, -f1`"
USERMAIL_PLACEHOLDER="${USERNAME_PLACEHOLDER}@${DNS_DOMAIN_PLACEHOLDER}"
USER_PROMPT_COLOR_PLACEHOLDER=GREEN # see colorsrc
ROOT_PROMPT_COLOR_PLACEHOLDER=YELLOW # see colorsrc
