#!/bin/sh
VROOT_PLACEHOLDER=~/vroot
ETC_PLACEHOLDER=$VROOT_PLACEHOLDER/etc
BIN_PLACEHOLDER=$VROOT_PLACEHOLDER/bin
SBIN_PLACEHOLDER=$VROOT_PLACEHOLDER/sbin
USERNAME_PLACEHOLDER="${USER}"
HOSTNAME_PLACEHOLDER="$(hostname -s)"
DNS_DOMAIN_PLACEHOLDER="$(hostname -d)"
USER_FULL_NAME_PLACEHOLDER="$(getent passwd "${USERNAME_PLACEHOLDER}" | cut -d: -f5 | cut -d, -f1)"
USERMAIL_PLACEHOLDER="${USERNAME_PLACEHOLDER}@${DNS_DOMAIN_PLACEHOLDER}"
WORKSPACE_PLACEHOLDER=~/workspace
REPO_ROOT_LIST_PLACEHOLDER=""
USER_PROMPT_COLOR_PLACEHOLDER=GREEN # see colorsrc
ROOT_PROMPT_COLOR_PLACEHOLDER=YELLOW # see colorsrc
