#!/bin/bash

PROGRAM=$(basename $0)
DESCRIPTION="block or unblock an IP"
PARAMS="IP..."
OPTIONS="[-hu] [-i | -o]"

usage()
{
	[ $1 -ne 0 ] && exec >&2

	cat << EOF
$PROGRAM - $DESCRIPTION
usage:
$PROGRAM $OPTIONS $PARAMS

options:
-h	help: show this help message and exit.
-u	unblock: unblock instead of blocking
-o	output: block outgoing traffic only
-i	input: block incoming traffic only

exit status:
1	options are bad
otherwise it is the return value of iptables
EOF

	exit $1
}

ACTION=--append
BLOCK_INBOUND=true
BLOCK_OUTBOUND=true
ACTION_NAME="blocking"
while getopts hiou OPTION; do
	case $OPTION in
		h) usage 0 ;;
		u) ACTION=--delete ; ACTION_NAME="unblocking" ;;
		o) BLOCK_INBOUND=false ;;
		i) BLOCK_OUTBOUND=false ;;
		\?) usage 1 ;;
	esac
done
shift $((OPTIND - 1))
if ! $BLOCK_INBOUND && ! $BLOCK_OUTBOUND; then
	errcho "$PROGRAM: nothing to do"
	usage 1
fi

iptables_cmd()
{
	local CHAIN="$1"
	iptables --table filter \
		$ACTION $CHAIN \
		--source $IP \
		--jump DROP
}

for IP in "$@"; do
	$BLOCK_INBOUND && echo "$ACTION_NAME $IP for inbound traffic" &&
		iptables_cmd INPUT &&
	$BLOCK_OUTBOUND && echo "$ACTION_NAME $IP for outbound traffic" &&
		iptables_cmd OUTPUT
done
